public enum ReplicationState {
    IDLE,
    CONNECTING,
    CONNECTED_AND_READY_TO_SEND_PING,
    SENT_PING,
    RECEIVED_PONG,
    SENT_REPLCONF_PORT,
    RECEIVED_REPLCONF_PORT_ACK,
    SENT_REPLCONF_CAPA,
    RECEIVED_REPLCONF_CAPA_ACK,
    SENT_PSYNC,
    AWAITING_RDB_BULK_STRING_HEADER,
    READING_RDB_BINARY,
    RECEIVED_RDB,
    READY_FOR_REPLICATION,
    ERROR
}